[build-system]
requires = [
    "setuptools", 
    "numpy", 
    "pandas", 
    "matplotlib", 
    "lightgbm", 
    "scikit-learn", 
    "ipykernel", 
    "geopy", 
    "h3", 
    "geopandas",
    "contextily",
]
build-backend = "setuptools.build_meta"
